---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: phos
description: My custom OS image for productivity.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
          - fptbb/fp-appimage-updater
    install:
      packages:
        - buildah
        - curl
        - fish
        - fp-appimage-updater
        - gcc # required by brew
        - git
        - podman
        - podman-compose
        - podman-docker
        - wget
        - zstd # required by Brew
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: brew
    auto-update: true
    update-interval: 1d
    update-wait-after-boot: 5s
    auto-upgrade: true
    upgrade-interval: 7d
    upgrade-wait-after-boot: 30s
    brew-analytics: true
    direct-pull: true

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: true
        repo:
          title: Flathub (system)
        install:
          - be.alexandervanhee.gradia
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - io.github.flattool.Warehouse
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - page.tesk.Refine
      - scope: user
        repo:
          title: Flathub (user)
        install:
          - app.zen_browser.zen
          - com.bitwarden.desktop
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.FileRoller
          - org.gnome.Firmware
          - org.gnome.Loupe
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Showtime
          - org.gnome.Snapshot
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.gitlab.somas.Apostrophe
          - org.libreoffice.LibreOffice
          - org.localsend.localsend_app
          - org.onlyoffice.desktopeditors

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter

  - type: gnome-extensions
    install:
      - 6670  # Bluetooth Battery Meter
      - 779   # Clipboard Indicator
      - 1319  # GSConnect
      - 10373 # Media Controls
      - 5964  # Quick Settings Audio Devices Hider
      - 6000  # Quick Settings Audio Devices Renamer
      - 5489  # Search Light

  - type: bling
    install:
      - dconf-update-service

  - type: systemd
    system:
      enabled:
        - docker.socket
        - podman.socket

  - type: os-release
    properties:
      ID: phos
      ID_LIKE: fedora
      NAME: Phosphorus
      PRETTY_NAME: Phos
      HOME_URL: https://github.com/ph-dev-br/phos
      DEFAULT_HOSTNAME: phos

  - type: signing
